// Curated puzzle library - REAL Reddit posts for fallback when API is unavailable
// These are actual posts pulled from Reddit via Devvit API
// All posts have valid IDs and permalinks that link to real Reddit content

import type { RedditPost } from '../../shared/types/puzzle';

/**
 * Curated library of REAL Reddit posts for fallback/seeding purposes.
 * These are cipher-friendly (no digits in title, mostly letters) and appropriate length.
 * All posts have been verified and pulled from actual Reddit content.
 */
export const CURATED_POSTS: RedditPost[] = [
  {
    id: '1r11mup',
    title: 'My wife got me a wallet that makes me look like Batman when I insert my license',
    subreddit: 'r/mildlyinteresting',
    author: 'u/BestAtTeamworkMan',
    upvotes: 125549,
    permalink: '/r/mildlyinteresting/comments/1r11mup/my_wife_got_me_a_wallet_that_makes_me_look_like/',
    createdUtc: 1770732328,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qvevem',
    title: 'recently got a place with my boyfriend and he thinks this is perfectly fine',
    subreddit: 'r/funny',
    author: 'u/daylightpiglet',
    upvotes: 117581,
    permalink: '/r/funny/comments/1qvevem/recently_got_a_place_with_my_boyfriend_and_he/',
    createdUtc: 1770179544,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qwkaw5',
    title: 'She came ready for the famous Turkish ice cream tricks… and got the normal service instead',
    subreddit: 'r/funny',
    author: 'u/Ok-Equivalent3810',
    upvotes: 69083,
    permalink: '/r/funny/comments/1qwkaw5/she_came_ready_for_the_famous_turkish_ice_cream/',
    createdUtc: 1770295463,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qybnsn',
    title: 'Woke up morning after party to all the silverware, oven knobs, and glasses in freezer stuck in bowls of ice',
    subreddit: 'r/funny',
    author: 'u/sarafina5',
    upvotes: 57855,
    permalink: '/r/funny/comments/1qybnsn/woke_up_morning_after_party_to_all_the_silverware/',
    createdUtc: 1770464358,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qzdlt1',
    title: 'How was the slumber party?',
    subreddit: 'r/funny',
    author: 'u/kingkongbiingbong',
    upvotes: 57829,
    permalink: '/r/funny/comments/1qzdlt1/how_was_the_slumber_party/',
    createdUtc: 1770568650,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qwqyuq',
    title: 'I found a knife perfectly imprinted into the bottom of my delivered subway sandwich…',
    subreddit: 'r/mildlyinteresting',
    author: 'u/One-Patient-3417',
    upvotes: 56097,
    permalink: '/r/mildlyinteresting/comments/1qwqyuq/i_found_a_knife_perfectly_imprinted_into_the/',
    createdUtc: 1770311217,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qzncj1',
    title: 'Walked past a Kevin from The Office look-alike contest today and took a picture of the winner',
    subreddit: 'r/mildlyinteresting',
    author: 'u/PsychologicalCost5',
    upvotes: 51739,
    permalink: '/r/mildlyinteresting/comments/1qzncj1/walked_past_a_kevin_from_the_office_lookalike/',
    createdUtc: 1770590710,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r045eq',
    title: 'Every time Bad Bunny said "Ey!" in the Halftime Show',
    subreddit: 'r/funny',
    author: 'u/dustin1776',
    upvotes: 49238,
    permalink: '/r/funny/comments/1r045eq/every_time_bad_bunny_said_ey_in_the_halftime_show/',
    createdUtc: 1770643556,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzpjm2',
    title: 'The fire department accidentally left behind a fire axe after clearing out our building.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Senior_Fish_Face',
    upvotes: 45439,
    permalink: '/r/mildlyinteresting/comments/1qzpjm2/the_fire_department_accidentally_left_behind_a/',
    createdUtc: 1770596659,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r1om0j',
    title: "Come on out we won't even touch you",
    subreddit: 'r/funny',
    author: 'u/Sad-Kiwi-3789',
    upvotes: 40424,
    permalink: '/r/funny/comments/1r1om0j/come_on_out_we_wont_even_touch_you/',
    createdUtc: 1770787109,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzqdz9',
    title: 'They ordered a self driving taxi and there was a parrot driving.',
    subreddit: 'r/funny',
    author: 'u/LorenBlaqe',
    upvotes: 38573,
    permalink: '/r/funny/comments/1qzqdz9/they_ordered_a_self_driving_taxi_and_there_was_a/',
    createdUtc: 1770599084,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qx28f0',
    title: 'Boyfriend, girlfriend, and her older brother in Honolulu',
    subreddit: 'r/funny',
    author: 'u/yawnjew',
    upvotes: 36671,
    permalink: '/r/funny/comments/1qx28f0/boyfriend_girlfriend_and_her_older_brother/',
    createdUtc: 1770336508,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r0fhou',
    title: 'Every third ad during the super bowl',
    subreddit: 'r/funny',
    author: 'u/kdrxyz',
    upvotes: 35392,
    permalink: '/r/funny/comments/1r0fhou/every_third_ad_during_the_super_bowl/',
    createdUtc: 1770668804,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzbszu',
    title: 'my roommate padlocked his towel',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Open_Donut_8682',
    upvotes: 35302,
    permalink: '/r/mildlyinteresting/comments/1qzbszu/my_roommate_padlocked_his_towel/',
    createdUtc: 1770564529,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r2bfpo',
    title: 'somebody left a chalice and dagger made of babybel cheese wax on my desk at university',
    subreddit: 'r/mildlyinteresting',
    author: 'u/coolgayroommate',
    upvotes: 33098,
    permalink: '/r/mildlyinteresting/comments/1r2bfpo/somebody_left_a_chalice_and_dagger_made_of/',
    createdUtc: 1770848091,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qxagnk',
    title: 'Reminds me of Boss Baby',
    subreddit: 'r/funny',
    author: 'u/Connect_Nerve_3923',
    upvotes: 32616,
    permalink: '/r/funny/comments/1qxagnk/reminds_me_of_boss_baby/',
    createdUtc: 1770360309,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qy3xnz',
    title: 'My birth control pill tablet ends with calling me a slut.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Goldensock',
    upvotes: 32341,
    permalink: '/r/mildlyinteresting/comments/1qy3xnz/my_birth_control_pill_tablet_ends_with_calling_me/',
    createdUtc: 1770437812,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qxwzsb',
    title: 'He forgot his keys and asked his cat to open the door',
    subreddit: 'r/funny',
    author: 'u/Ok-Equivalent3810',
    upvotes: 29360,
    permalink: '/r/funny/comments/1qxwzsb/he_forgot_his_keys_and_asked_his_cat_to_open_the/',
    createdUtc: 1770419186,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qvp387',
    title: 'Recently got a place with my girlfriend. She thinks this is totally fine',
    subreddit: 'r/funny',
    author: 'u/AnthMosk',
    upvotes: 28508,
    permalink: '/r/funny/comments/1qvp387/recently_got_a_place_with_my_girlfriend_she/',
    createdUtc: 1770213070,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qwiq05',
    title: 'The pig with a wooden leg',
    subreddit: 'r/funny',
    author: 'u/JibunNiMakenai',
    upvotes: 27885,
    permalink: '/r/funny/comments/1qwiq05/the_pig_with_a_wooden_leg/',
    createdUtc: 1770290543,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qulwcb',
    title: "nooo don't stop living, you're too sexy aha",
    subreddit: 'r/wholesomememes',
    author: 'u/atombub',
    upvotes: 27199,
    permalink: '/r/wholesomememes/comments/1qulwcb/nooo_dont_stop_living_youre_too_sexy_aha/',
    createdUtc: 1770104824,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzng34',
    title: 'TIL Even though Pedialyte is marketed towards children, over a third of sales come from adults with hangovers.',
    subreddit: 'r/todayilearned',
    author: 'u/redmambo_no6',
    upvotes: 26416,
    permalink: '/r/todayilearned/comments/1qzng34/til_even_though_pedialyte_is_marketed_towards/',
    createdUtc: 1770590957,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qxr7d0',
    title: 'The wear pattern on these monkey bars shows how far most kids get',
    subreddit: 'r/mildlyinteresting',
    author: 'u/dumbfuck',
    upvotes: 26253,
    permalink: '/r/mildlyinteresting/comments/1qxr7d0/the_wear_pattern_on_these_monkey_bars_shows_how/',
    createdUtc: 1770405821,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qxpkv9',
    title: 'Care facility residents smoking weed instead of cigarettes',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Iitaps_Missiciv',
    upvotes: 25762,
    permalink: '/r/mildlyinteresting/comments/1qxpkv9/care_facility_residents_smoking_weed_instead_of/',
    createdUtc: 1770402306,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qye7lg',
    title: 'A random tablet end has highjacked its way into my paracetamol blister pack',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Aishas_Star',
    upvotes: 24679,
    permalink: '/r/mildlyinteresting/comments/1qye7lg/a_random_tablet_end_has_highjacked_its_way_into/',
    createdUtc: 1770471990,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r1nfqp',
    title: 'Bottom of the bowl cracked in a circle and Snoopy popped out perfectly',
    subreddit: 'r/mildlyinteresting',
    author: 'u/fairytale-fairy',
    upvotes: 24594,
    permalink: '/r/mildlyinteresting/comments/1r1nfqp/bottom_of_the_bowl_cracked_in_a_circle_and_snoopy/',
    createdUtc: 1770783573,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r17c44',
    title: 'My dorm uses tape to make warm lights',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Western-Ad-4457',
    upvotes: 18084,
    permalink: '/r/mildlyinteresting/comments/1r17c44/my_dorm_uses_tape_to_make_warm_lights/',
    createdUtc: 1770745020,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzl2hf',
    title: 'He knows how to make me smile',
    subreddit: 'r/wholesomememes',
    author: 'u/Princess-honeysuckle',
    upvotes: 18001,
    permalink: '/r/wholesomememes/comments/1qzl2hf/he_knows_how_to_make_me_smile/',
    createdUtc: 1770585276,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzqz4k',
    title: 'what did yall think of the bad bunny halftime show?',
    subreddit: 'r/AskReddit',
    author: 'u/Serious-Kale-5694',
    upvotes: 17959,
    permalink: '/r/AskReddit/comments/1qzqz4k/what_did_yall_think_of_the_bad_bunny_halftime_show/',
    createdUtc: 1770600890,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qxk1jb',
    title: 'Friend of mine got this in the mail, such considerate neighbors',
    subreddit: 'r/funny',
    author: 'u/NicetoNietzsche',
    upvotes: 17930,
    permalink: '/r/funny/comments/1qxk1jb/friend_of_mine_got_this_in_the_mail_such/',
    createdUtc: 1770390360,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzy4jm',
    title: "Imagine waking up this morning knowing you're going into work as a shrub",
    subreddit: 'r/funny',
    author: 'u/Jazzlike-Tie-354',
    upvotes: 17121,
    permalink: '/r/funny/comments/1qzy4jm/imagine_waking_up_this_morning_knowing_youre/',
    createdUtc: 1770622947,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qxin1n',
    title: "I wasn't expecting this ending.",
    subreddit: 'r/funny',
    author: 'u/father_of_twitch',
    upvotes: 15390,
    permalink: '/r/funny/comments/1qxin1n/i_wasnt_expecting_this_ending/',
    createdUtc: 1770387042,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qyqjfv',
    title: 'My Burger King has no burgers',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Tycoonster',
    upvotes: 14487,
    permalink: '/r/mildlyinteresting/comments/1qyqjfv/my_burger_king_has_no_burgers/',
    createdUtc: 1770501030,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzkosq',
    title: 'What hobby screams "this is my entire personality now"?',
    subreddit: 'r/AskReddit',
    author: 'u/WilliamInBlack',
    upvotes: 14251,
    permalink: '/r/AskReddit/comments/1qzkosq/what_hobby_screams_this_is_my_entire_personality/',
    createdUtc: 1770584433,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzwgcp',
    title: 'I found my doppelganger on a resteraunt wall in Oregon.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Electrical_Remote_18',
    upvotes: 13668,
    permalink: '/r/mildlyinteresting/comments/1qzwgcp/i_found_my_doppelganger_on_a_resteraunt_wall_in/',
    createdUtc: 1770617115,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qxk73v',
    title: 'My cat is so small I can easily put him in a sock.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/IModernVerseI',
    upvotes: 12512,
    permalink: '/r/mildlyinteresting/comments/1qxk73v/my_cat_is_so_small_i_can_easily_put_him_in_a_sock/',
    createdUtc: 1770390721,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qya7kg',
    title: 'The treasure was inside you all along',
    subreddit: 'r/wholesomememes',
    author: 'u/Dark-Protocol',
    upvotes: 12090,
    permalink: '/r/wholesomememes/comments/1qya7kg/the_treasure_was_inside_you_all_along/',
    createdUtc: 1770459170,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r2co0p',
    title: 'TIL that salted raw celery used to be the third most popular dish on New York menus and more expensive than caviar due to issues with growing it.',
    subreddit: 'r/todayilearned',
    author: 'u/Sanguinusshiboleth',
    upvotes: 11956,
    permalink: '/r/todayilearned/comments/1r2co0p/til_that_salted_raw_celery_used_to_be_the_third/',
    createdUtc: 1770850975,
    cipherFriendly: true,
    difficulty: 'hard',
  },
  {
    id: '1qn1gnc',
    title: 'I love my wife very much.',
    subreddit: 'r/wholesomememes',
    author: 'u/Jack-mclaughlin89',
    upvotes: 11758,
    permalink: '/r/wholesomememes/comments/1qn1gnc/i_love_my_wife_very_much/',
    createdUtc: 1769389394,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r09bjh',
    title: 'The spot on my dogs paw pad has grown since October.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/waowediting',
    upvotes: 11516,
    permalink: '/r/mildlyinteresting/comments/1r09bjh/the_spot_on_my_dogs_paw_pad_has_grown_since/',
    createdUtc: 1770655677,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qzmxth',
    title: "The frosting to cake ratio at my nephew's birthday party.",
    subreddit: 'r/mildlyinteresting',
    author: 'u/Crossover9988',
    upvotes: 11310,
    permalink: '/r/mildlyinteresting/comments/1qzmxth/the_frosting_to_cake_ratio_at_my_nephews_birthday/',
    createdUtc: 1770589690,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r15ep5',
    title: 'TIL French scientist Étienne Klein was criticized after sharing a fake image of Proxima Centauri that turned out to be chorizo',
    subreddit: 'r/todayilearned',
    author: 'u/Brendawg324',
    upvotes: 10441,
    permalink: '/r/todayilearned/comments/1r15ep5/til_french_scientist_étienne_klein_was_criticized/',
    createdUtc: 1770740861,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1qzevjy',
    title: 'TIL that up until the past year, Oscar judges DID NOT have to watch the movies they were giving the awards to.',
    subreddit: 'r/todayilearned',
    author: 'u/GossipBottom',
    upvotes: 10372,
    permalink: '/r/todayilearned/comments/1qzevjy/til_that_up_until_the_past_year_oscar_judges_did/',
    createdUtc: 1770571486,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r0bqkf',
    title: 'LPT: Do not add your work colleagues as your facebook friends',
    subreddit: 'r/LifeProTips',
    author: 'u/zztop610',
    upvotes: 10001,
    permalink: '/r/LifeProTips/comments/1r0bqkf/lpt_do_not_add_your_work_colleagues_as_your/',
    createdUtc: 1770660786,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r19h33',
    title: 'Non-Americans of Reddit, what is an American thing you see in movies that you thought was fake but is actually real?',
    subreddit: 'r/AskReddit',
    author: 'u/Unlikely_Praline9442',
    upvotes: 9880,
    permalink: '/r/AskReddit/comments/1r19h33/nonamericans_of_reddit_what_is_an_american_thing/',
    createdUtc: 1770749552,
    cipherFriendly: true,
    difficulty: 'medium',
  },
  {
    id: '1r29p49',
    title: "Went to Musée d'Orsay today…",
    subreddit: 'r/funny',
    author: 'u/kafkakerlake',
    upvotes: 9872,
    permalink: '/r/funny/comments/1r29p49/went_to_musée_dorsay_today/',
    createdUtc: 1770844129,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r2h7wl',
    title: 'My nails grow in a wavy pattern',
    subreddit: 'r/mildlyinteresting',
    author: 'u/Toucan_Toucan',
    upvotes: 9559,
    permalink: '/r/mildlyinteresting/comments/1r2h7wl/my_nails_grow_in_a_wavy_pattern/',
    createdUtc: 1770862854,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1qyvsai',
    title: "My neighbor putting everyone else's snowman to shame",
    subreddit: 'r/mildlyinteresting',
    author: 'u/ForFoxSakeCole',
    upvotes: 8904,
    permalink: '/r/mildlyinteresting/comments/1qyvsai/my_neighbor_putting_everyone_elses_snowman_to/',
    createdUtc: 1770514714,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r1a6bk',
    title: 'My free Lays from the Super Bowl ad actually came in.',
    subreddit: 'r/mildlyinteresting',
    author: 'u/CardDragon',
    upvotes: 8810,
    permalink: '/r/mildlyinteresting/comments/1r1a6bk/my_free_lays_from_the_super_bowl_ad_actually_came/',
    createdUtc: 1770751036,
    cipherFriendly: true,
    difficulty: 'easy',
  },
  {
    id: '1r251ug',
    title: 'Found a roast list in my little sister room',
    subreddit: 'r/funny',
    author: 'u/Additional-Rub664',
    upvotes: 8006,
    permalink: '/r/funny/comments/1r251ug/found_a_roast_list_in_my_little_sister_room/',
    createdUtc: 1770833896,
    cipherFriendly: true,
    difficulty: 'easy',
  },
];

/**
 * Get a random post from the curated library
 */
export function getRandomCuratedPost(): RedditPost {
  if (CURATED_POSTS.length === 0) {
    throw new Error('Curated post library is empty');
  }
  return CURATED_POSTS[Math.floor(Math.random() * CURATED_POSTS.length)];
}

/**
 * Get a curated post by index (for deterministic selection)
 */
export function getCuratedPostByIndex(index: number): RedditPost {
  if (CURATED_POSTS.length === 0) {
    throw new Error('Curated post library is empty');
  }
  return CURATED_POSTS[index % CURATED_POSTS.length];
}

/**
 * Get all curated posts
 */
export function getAllCuratedPosts(): RedditPost[] {
  return [...CURATED_POSTS];
}
